// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalTrainerWeb.Data;

namespace PersonalTrainerWeb.Migrations
{
    [DbContext(typeof(PersonalTrainerContext))]
    [Migration("20210110111223_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PersonalTrainerWeb.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Greutate")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdusID")
                        .HasColumnType("int");

                    b.Property<int>("Varsta")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProdusID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("PersonalTrainerWeb.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("SuplimentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SuplimentID")
                        .IsUnique();

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("PersonalTrainerWeb.Models.Supliment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cantitate")
                        .HasColumnType("int");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.ToTable("Supliment");
                });

            modelBuilder.Entity("PersonalTrainerWeb.Models.Client", b =>
                {
                    b.HasOne("PersonalTrainerWeb.Models.Produs", "Produs")
                        .WithMany("Clienti")
                        .HasForeignKey("ProdusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("PersonalTrainerWeb.Models.Produs", b =>
                {
                    b.HasOne("PersonalTrainerWeb.Models.Supliment", "Supliment")
                        .WithOne("Produs")
                        .HasForeignKey("PersonalTrainerWeb.Models.Produs", "SuplimentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supliment");
                });

            modelBuilder.Entity("PersonalTrainerWeb.Models.Produs", b =>
                {
                    b.Navigation("Clienti");
                });

            modelBuilder.Entity("PersonalTrainerWeb.Models.Supliment", b =>
                {
                    b.Navigation("Produs");
                });
#pragma warning restore 612, 618
        }
    }
}
